//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.ReferenciaRemota {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cargo", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Cargo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCargoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCargo {
            get {
                return this.idCargoField;
            }
            set {
                if ((this.idCargoField.Equals(value) != true)) {
                    this.idCargoField = value;
                    this.RaisePropertyChanged("idCargo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Titulo", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Titulo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTitulo {
            get {
                return this.idTituloField;
            }
            set {
                if ((this.idTituloField.Equals(value) != true)) {
                    this.idTituloField = value;
                    this.RaisePropertyChanged("idTitulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provincia", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Provincia : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                if ((this.idProvinciaField.Equals(value) != true)) {
                    this.idProvinciaField = value;
                    this.RaisePropertyChanged("idProvincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contacto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Contacto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCargoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idTituloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string numCedulaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCargo {
            get {
                return this.idCargoField;
            }
            set {
                if ((this.idCargoField.Equals(value) != true)) {
                    this.idCargoField = value;
                    this.RaisePropertyChanged("idCargo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idContacto {
            get {
                return this.idContactoField;
            }
            set {
                if ((this.idContactoField.Equals(value) != true)) {
                    this.idContactoField = value;
                    this.RaisePropertyChanged("idContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idTitulo {
            get {
                return this.idTituloField;
            }
            set {
                if ((this.idTituloField.Equals(value) != true)) {
                    this.idTituloField = value;
                    this.RaisePropertyChanged("idTitulo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string numCedula {
            get {
                return this.numCedulaField;
            }
            set {
                if ((object.ReferenceEquals(this.numCedulaField, value) != true)) {
                    this.numCedulaField = value;
                    this.RaisePropertyChanged("numCedula");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Organizacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Organizacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CiudadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SitioWebField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idOrganizacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idProvinciaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ciudad {
            get {
                return this.CiudadField;
            }
            set {
                if ((object.ReferenceEquals(this.CiudadField, value) != true)) {
                    this.CiudadField = value;
                    this.RaisePropertyChanged("Ciudad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoPostal {
            get {
                return this.CodigoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPostalField, value) != true)) {
                    this.CodigoPostalField = value;
                    this.RaisePropertyChanged("CodigoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SitioWeb {
            get {
                return this.SitioWebField;
            }
            set {
                if ((object.ReferenceEquals(this.SitioWebField, value) != true)) {
                    this.SitioWebField = value;
                    this.RaisePropertyChanged("SitioWeb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idOrganizacion {
            get {
                return this.idOrganizacionField;
            }
            set {
                if ((this.idOrganizacionField.Equals(value) != true)) {
                    this.idOrganizacionField = value;
                    this.RaisePropertyChanged("idOrganizacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idProvincia {
            get {
                return this.idProvinciaField;
            }
            set {
                if ((this.idProvinciaField.Equals(value) != true)) {
                    this.idProvinciaField = value;
                    this.RaisePropertyChanged("idProvincia");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoriaCorreo", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class CategoriaCorreo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaCorreoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoriaCorreo {
            get {
                return this.idCategoriaCorreoField;
            }
            set {
                if ((this.idCategoriaCorreoField.Equals(value) != true)) {
                    this.idCategoriaCorreoField = value;
                    this.RaisePropertyChanged("idCategoriaCorreo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GrupoCostos", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class GrupoCostos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idGrupoCostosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idGrupoCostos {
            get {
                return this.idGrupoCostosField;
            }
            set {
                if ((this.idGrupoCostosField.Equals(value) != true)) {
                    this.idGrupoCostosField = value;
                    this.RaisePropertyChanged("idGrupoCostos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReferenciaRemota.IGestionDocumento")]
    public interface IGestionDocumento {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerCargo", ReplyAction="http://tempuri.org/IGestionDocumento/LeerCargoResponse")]
        Cliente.ReferenciaRemota.Cargo[] LeerCargo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerCargo", ReplyAction="http://tempuri.org/IGestionDocumento/LeerCargoResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Cargo[]> LeerCargoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/LeerTituloResponse")]
        Cliente.ReferenciaRemota.Titulo[] LeerTitulo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/LeerTituloResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Titulo[]> LeerTituloAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/LeerProvinciaResponse")]
        Cliente.ReferenciaRemota.Provincia[] LeerProvincia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/LeerProvinciaResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Provincia[]> LeerProvinciaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerContacto", ReplyAction="http://tempuri.org/IGestionDocumento/LeerContactoResponse")]
        Cliente.ReferenciaRemota.Contacto[] LeerContacto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerContacto", ReplyAction="http://tempuri.org/IGestionDocumento/LeerContactoResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Contacto[]> LeerContactoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/LeerOrganizacionResponse")]
        Cliente.ReferenciaRemota.Organizacion[] LeerOrganizacion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/LeerOrganizacionResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Organizacion[]> LeerOrganizacionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/LeerCategoriaCorreoResponse")]
        Cliente.ReferenciaRemota.CategoriaCorreo[] LeerCategoriaCorreo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/LeerCategoriaCorreoResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.CategoriaCorreo[]> LeerCategoriaCorreoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/LeerGrupoCostoResponse")]
        Cliente.ReferenciaRemota.GrupoCostos[] LeerGrupoCosto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/LeerGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/LeerGrupoCostoResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.GrupoCostos[]> LeerGrupoCostoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarContacto", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarContactoResponse")]
        void AgregarContacto(int idCargo, int idTitulo, string nombre, string apellido, string numCedula, string correo, string numTelefonico, string celular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarContacto", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarContactoResponse")]
        System.Threading.Tasks.Task AgregarContactoAsync(int idCargo, int idTitulo, string nombre, string apellido, string numCedula, string correo, string numTelefonico, string celular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarOrganizacionResponse")]
        void AgregarOrganizacion(string nombreOrg, string direccionOrg, string codigoPostal, string ciudadOrg, int idProvincia, string telefonoOrg, string correoOrg, string sitioWebOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarOrganizacionResponse")]
        System.Threading.Tasks.Task AgregarOrganizacionAsync(string nombreOrg, string direccionOrg, string codigoPostal, string ciudadOrg, int idProvincia, string telefonoOrg, string correoOrg, string sitioWebOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarProvinciaResponse")]
        void AgregarProvincia(string nombreProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarProvinciaResponse")]
        System.Threading.Tasks.Task AgregarProvinciaAsync(string nombreProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarCargo", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarCargoResponse")]
        void AgregarCargo(string nombreCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarCargo", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarCargoResponse")]
        System.Threading.Tasks.Task AgregarCargoAsync(string nombreCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarCategoriaCorreoResponse")]
        void AgregarCategoriaCorreo(string nombreCategoriaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarCategoriaCorreoResponse")]
        System.Threading.Tasks.Task AgregarCategoriaCorreoAsync(string nombreCategoriaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarGrupoCostoResponse")]
        void AgregarGrupoCosto(string nombreGrupoCostos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarGrupoCostoResponse")]
        System.Threading.Tasks.Task AgregarGrupoCostoAsync(string nombreGrupoCostos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarTituloResponse")]
        void AgregarTitulo(string nombreTitulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/AgregarTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/AgregarTituloResponse")]
        System.Threading.Tasks.Task AgregarTituloAsync(string nombreTitulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarContacto", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarContactoResponse")]
        void EliminarContacto(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarContacto", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarContactoResponse")]
        System.Threading.Tasks.Task EliminarContactoAsync(int idContacto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarOrganizacionResponse")]
        void EliminarOrganizacion(int idOrganizacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarOrganizacionResponse")]
        System.Threading.Tasks.Task EliminarOrganizacionAsync(int idOrganizacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarProvinciaResponse")]
        void EliminarProvincia(int idProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarProvinciaResponse")]
        System.Threading.Tasks.Task EliminarProvinciaAsync(int idProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarCargo", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarCargoResponse")]
        void EliminarCargo(int idCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarCargo", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarCargoResponse")]
        System.Threading.Tasks.Task EliminarCargoAsync(int idCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarCategoriaCorreoResponse")]
        void EliminarCategoriaCorreo(int idCategoriaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarCategoriaCorreoResponse")]
        System.Threading.Tasks.Task EliminarCategoriaCorreoAsync(int idCategoriaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarGrupoCostoResponse")]
        void EliminarGrupoCosto(int idGrupoCosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarGrupoCostoResponse")]
        System.Threading.Tasks.Task EliminarGrupoCostoAsync(int idGrupoCosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarTituloResponse")]
        void EliminarTitulo(int idTitulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EliminarTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/EliminarTituloResponse")]
        System.Threading.Tasks.Task EliminarTituloAsync(int idTitulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarContacto", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarContactoResponse")]
        Cliente.ReferenciaRemota.Contacto BuscarContacto(string numCedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarContacto", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarContactoResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Contacto> BuscarContactoAsync(string numCedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarOrganizacionResponse")]
        Cliente.ReferenciaRemota.Organizacion BuscarOrganizacion(int idOrganizacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarOrganizacionResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Organizacion> BuscarOrganizacionAsync(int idOrganizacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarOrg_Nombre", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarOrg_NombreResponse")]
        Cliente.ReferenciaRemota.Organizacion BuscarOrg_Nombre(string nombreOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarOrg_Nombre", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarOrg_NombreResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Organizacion> BuscarOrg_NombreAsync(string nombreOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarOrg_Direccion", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarOrg_DireccionResponse")]
        Cliente.ReferenciaRemota.Organizacion BuscarOrg_Direccion(string direccionOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarOrg_Direccion", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarOrg_DireccionResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Organizacion> BuscarOrg_DireccionAsync(string direccionOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarProvinciaResponse")]
        Cliente.ReferenciaRemota.Provincia BuscarProvincia(string nombreProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarProvinciaResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Provincia> BuscarProvinciaAsync(string nombreProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarCargo", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarCargoResponse")]
        Cliente.ReferenciaRemota.Cargo BuscarCargo(string nombreCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarCargo", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarCargoResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Cargo> BuscarCargoAsync(string nombreCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarCategoriaCorreoResponse")]
        Cliente.ReferenciaRemota.CategoriaCorreo BuscarCategoriaCorreo(string nombreCategoriaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarCategoriaCorreoResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.CategoriaCorreo> BuscarCategoriaCorreoAsync(string nombreCategoriaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarGrupoCostoResponse")]
        Cliente.ReferenciaRemota.GrupoCostos BuscarGrupoCosto(string nombreGrupoCosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarGrupoCostoResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.GrupoCostos> BuscarGrupoCostoAsync(string nombreGrupoCosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarTituloResponse")]
        Cliente.ReferenciaRemota.Titulo BuscarTitulo(string nombreTitulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/BuscarTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/BuscarTituloResponse")]
        System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Titulo> BuscarTituloAsync(string nombreTitulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarContacto", ReplyAction="http://tempuri.org/IGestionDocumento/EditarContactoResponse")]
        void EditarContacto(int idContacto, int idCargo, int idTitulo, string nombre, string apellido, string numCedula, string correo, string numTelefonico, string celular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarContacto", ReplyAction="http://tempuri.org/IGestionDocumento/EditarContactoResponse")]
        System.Threading.Tasks.Task EditarContactoAsync(int idContacto, int idCargo, int idTitulo, string nombre, string apellido, string numCedula, string correo, string numTelefonico, string celular);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/EditarOrganizacionResponse")]
        void EditarOrganizacion(int idOrganizacion, string nombreOrg, string direccionOrg, string codigoPostal, string ciudadOrg, int idProvincia, string telefonoOrg, string correoOrg, string sitioWebOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarOrganizacion", ReplyAction="http://tempuri.org/IGestionDocumento/EditarOrganizacionResponse")]
        System.Threading.Tasks.Task EditarOrganizacionAsync(int idOrganizacion, string nombreOrg, string direccionOrg, string codigoPostal, string ciudadOrg, int idProvincia, string telefonoOrg, string correoOrg, string sitioWebOrg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/EditarProvinciaResponse")]
        void EditarProvincia(int idProvincia, string nombreProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarProvincia", ReplyAction="http://tempuri.org/IGestionDocumento/EditarProvinciaResponse")]
        System.Threading.Tasks.Task EditarProvinciaAsync(int idProvincia, string nombreProvincia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarCargo", ReplyAction="http://tempuri.org/IGestionDocumento/EditarCargoResponse")]
        void EditarCargo(int idCargo, string nombreCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarCargo", ReplyAction="http://tempuri.org/IGestionDocumento/EditarCargoResponse")]
        System.Threading.Tasks.Task EditarCargoAsync(int idCargo, string nombreCargo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/EditarCategoriaCorreoResponse")]
        void EditarCategoriaCorreo(int idCategoriaCorreo, string nombreCategoriaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarCategoriaCorreo", ReplyAction="http://tempuri.org/IGestionDocumento/EditarCategoriaCorreoResponse")]
        System.Threading.Tasks.Task EditarCategoriaCorreoAsync(int idCategoriaCorreo, string nombreCategoriaCorreo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/EditarGrupoCostoResponse")]
        void EditarGrupoCosto(int idGrupoCosto, string nombreGrupoCosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarGrupoCosto", ReplyAction="http://tempuri.org/IGestionDocumento/EditarGrupoCostoResponse")]
        System.Threading.Tasks.Task EditarGrupoCostoAsync(int idGrupoCosto, string nombreGrupoCosto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/EditarTituloResponse")]
        void EditarTitulo(int idTitulo, string nombreTitulo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionDocumento/EditarTitulo", ReplyAction="http://tempuri.org/IGestionDocumento/EditarTituloResponse")]
        System.Threading.Tasks.Task EditarTituloAsync(int idTitulo, string nombreTitulo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionDocumentoChannel : Cliente.ReferenciaRemota.IGestionDocumento, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionDocumentoClient : System.ServiceModel.ClientBase<Cliente.ReferenciaRemota.IGestionDocumento>, Cliente.ReferenciaRemota.IGestionDocumento {
        
        public GestionDocumentoClient() {
        }
        
        public GestionDocumentoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionDocumentoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionDocumentoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionDocumentoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliente.ReferenciaRemota.Cargo[] LeerCargo() {
            return base.Channel.LeerCargo();
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Cargo[]> LeerCargoAsync() {
            return base.Channel.LeerCargoAsync();
        }
        
        public Cliente.ReferenciaRemota.Titulo[] LeerTitulo() {
            return base.Channel.LeerTitulo();
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Titulo[]> LeerTituloAsync() {
            return base.Channel.LeerTituloAsync();
        }
        
        public Cliente.ReferenciaRemota.Provincia[] LeerProvincia() {
            return base.Channel.LeerProvincia();
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Provincia[]> LeerProvinciaAsync() {
            return base.Channel.LeerProvinciaAsync();
        }
        
        public Cliente.ReferenciaRemota.Contacto[] LeerContacto() {
            return base.Channel.LeerContacto();
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Contacto[]> LeerContactoAsync() {
            return base.Channel.LeerContactoAsync();
        }
        
        public Cliente.ReferenciaRemota.Organizacion[] LeerOrganizacion() {
            return base.Channel.LeerOrganizacion();
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Organizacion[]> LeerOrganizacionAsync() {
            return base.Channel.LeerOrganizacionAsync();
        }
        
        public Cliente.ReferenciaRemota.CategoriaCorreo[] LeerCategoriaCorreo() {
            return base.Channel.LeerCategoriaCorreo();
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.CategoriaCorreo[]> LeerCategoriaCorreoAsync() {
            return base.Channel.LeerCategoriaCorreoAsync();
        }
        
        public Cliente.ReferenciaRemota.GrupoCostos[] LeerGrupoCosto() {
            return base.Channel.LeerGrupoCosto();
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.GrupoCostos[]> LeerGrupoCostoAsync() {
            return base.Channel.LeerGrupoCostoAsync();
        }
        
        public void AgregarContacto(int idCargo, int idTitulo, string nombre, string apellido, string numCedula, string correo, string numTelefonico, string celular) {
            base.Channel.AgregarContacto(idCargo, idTitulo, nombre, apellido, numCedula, correo, numTelefonico, celular);
        }
        
        public System.Threading.Tasks.Task AgregarContactoAsync(int idCargo, int idTitulo, string nombre, string apellido, string numCedula, string correo, string numTelefonico, string celular) {
            return base.Channel.AgregarContactoAsync(idCargo, idTitulo, nombre, apellido, numCedula, correo, numTelefonico, celular);
        }
        
        public void AgregarOrganizacion(string nombreOrg, string direccionOrg, string codigoPostal, string ciudadOrg, int idProvincia, string telefonoOrg, string correoOrg, string sitioWebOrg) {
            base.Channel.AgregarOrganizacion(nombreOrg, direccionOrg, codigoPostal, ciudadOrg, idProvincia, telefonoOrg, correoOrg, sitioWebOrg);
        }
        
        public System.Threading.Tasks.Task AgregarOrganizacionAsync(string nombreOrg, string direccionOrg, string codigoPostal, string ciudadOrg, int idProvincia, string telefonoOrg, string correoOrg, string sitioWebOrg) {
            return base.Channel.AgregarOrganizacionAsync(nombreOrg, direccionOrg, codigoPostal, ciudadOrg, idProvincia, telefonoOrg, correoOrg, sitioWebOrg);
        }
        
        public void AgregarProvincia(string nombreProvincia) {
            base.Channel.AgregarProvincia(nombreProvincia);
        }
        
        public System.Threading.Tasks.Task AgregarProvinciaAsync(string nombreProvincia) {
            return base.Channel.AgregarProvinciaAsync(nombreProvincia);
        }
        
        public void AgregarCargo(string nombreCargo) {
            base.Channel.AgregarCargo(nombreCargo);
        }
        
        public System.Threading.Tasks.Task AgregarCargoAsync(string nombreCargo) {
            return base.Channel.AgregarCargoAsync(nombreCargo);
        }
        
        public void AgregarCategoriaCorreo(string nombreCategoriaCorreo) {
            base.Channel.AgregarCategoriaCorreo(nombreCategoriaCorreo);
        }
        
        public System.Threading.Tasks.Task AgregarCategoriaCorreoAsync(string nombreCategoriaCorreo) {
            return base.Channel.AgregarCategoriaCorreoAsync(nombreCategoriaCorreo);
        }
        
        public void AgregarGrupoCosto(string nombreGrupoCostos) {
            base.Channel.AgregarGrupoCosto(nombreGrupoCostos);
        }
        
        public System.Threading.Tasks.Task AgregarGrupoCostoAsync(string nombreGrupoCostos) {
            return base.Channel.AgregarGrupoCostoAsync(nombreGrupoCostos);
        }
        
        public void AgregarTitulo(string nombreTitulo) {
            base.Channel.AgregarTitulo(nombreTitulo);
        }
        
        public System.Threading.Tasks.Task AgregarTituloAsync(string nombreTitulo) {
            return base.Channel.AgregarTituloAsync(nombreTitulo);
        }
        
        public void EliminarContacto(int idContacto) {
            base.Channel.EliminarContacto(idContacto);
        }
        
        public System.Threading.Tasks.Task EliminarContactoAsync(int idContacto) {
            return base.Channel.EliminarContactoAsync(idContacto);
        }
        
        public void EliminarOrganizacion(int idOrganizacion) {
            base.Channel.EliminarOrganizacion(idOrganizacion);
        }
        
        public System.Threading.Tasks.Task EliminarOrganizacionAsync(int idOrganizacion) {
            return base.Channel.EliminarOrganizacionAsync(idOrganizacion);
        }
        
        public void EliminarProvincia(int idProvincia) {
            base.Channel.EliminarProvincia(idProvincia);
        }
        
        public System.Threading.Tasks.Task EliminarProvinciaAsync(int idProvincia) {
            return base.Channel.EliminarProvinciaAsync(idProvincia);
        }
        
        public void EliminarCargo(int idCargo) {
            base.Channel.EliminarCargo(idCargo);
        }
        
        public System.Threading.Tasks.Task EliminarCargoAsync(int idCargo) {
            return base.Channel.EliminarCargoAsync(idCargo);
        }
        
        public void EliminarCategoriaCorreo(int idCategoriaCorreo) {
            base.Channel.EliminarCategoriaCorreo(idCategoriaCorreo);
        }
        
        public System.Threading.Tasks.Task EliminarCategoriaCorreoAsync(int idCategoriaCorreo) {
            return base.Channel.EliminarCategoriaCorreoAsync(idCategoriaCorreo);
        }
        
        public void EliminarGrupoCosto(int idGrupoCosto) {
            base.Channel.EliminarGrupoCosto(idGrupoCosto);
        }
        
        public System.Threading.Tasks.Task EliminarGrupoCostoAsync(int idGrupoCosto) {
            return base.Channel.EliminarGrupoCostoAsync(idGrupoCosto);
        }
        
        public void EliminarTitulo(int idTitulo) {
            base.Channel.EliminarTitulo(idTitulo);
        }
        
        public System.Threading.Tasks.Task EliminarTituloAsync(int idTitulo) {
            return base.Channel.EliminarTituloAsync(idTitulo);
        }
        
        public Cliente.ReferenciaRemota.Contacto BuscarContacto(string numCedula) {
            return base.Channel.BuscarContacto(numCedula);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Contacto> BuscarContactoAsync(string numCedula) {
            return base.Channel.BuscarContactoAsync(numCedula);
        }
        
        public Cliente.ReferenciaRemota.Organizacion BuscarOrganizacion(int idOrganizacion) {
            return base.Channel.BuscarOrganizacion(idOrganizacion);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Organizacion> BuscarOrganizacionAsync(int idOrganizacion) {
            return base.Channel.BuscarOrganizacionAsync(idOrganizacion);
        }
        
        public Cliente.ReferenciaRemota.Organizacion BuscarOrg_Nombre(string nombreOrg) {
            return base.Channel.BuscarOrg_Nombre(nombreOrg);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Organizacion> BuscarOrg_NombreAsync(string nombreOrg) {
            return base.Channel.BuscarOrg_NombreAsync(nombreOrg);
        }
        
        public Cliente.ReferenciaRemota.Organizacion BuscarOrg_Direccion(string direccionOrg) {
            return base.Channel.BuscarOrg_Direccion(direccionOrg);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Organizacion> BuscarOrg_DireccionAsync(string direccionOrg) {
            return base.Channel.BuscarOrg_DireccionAsync(direccionOrg);
        }
        
        public Cliente.ReferenciaRemota.Provincia BuscarProvincia(string nombreProvincia) {
            return base.Channel.BuscarProvincia(nombreProvincia);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Provincia> BuscarProvinciaAsync(string nombreProvincia) {
            return base.Channel.BuscarProvinciaAsync(nombreProvincia);
        }
        
        public Cliente.ReferenciaRemota.Cargo BuscarCargo(string nombreCargo) {
            return base.Channel.BuscarCargo(nombreCargo);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Cargo> BuscarCargoAsync(string nombreCargo) {
            return base.Channel.BuscarCargoAsync(nombreCargo);
        }
        
        public Cliente.ReferenciaRemota.CategoriaCorreo BuscarCategoriaCorreo(string nombreCategoriaCorreo) {
            return base.Channel.BuscarCategoriaCorreo(nombreCategoriaCorreo);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.CategoriaCorreo> BuscarCategoriaCorreoAsync(string nombreCategoriaCorreo) {
            return base.Channel.BuscarCategoriaCorreoAsync(nombreCategoriaCorreo);
        }
        
        public Cliente.ReferenciaRemota.GrupoCostos BuscarGrupoCosto(string nombreGrupoCosto) {
            return base.Channel.BuscarGrupoCosto(nombreGrupoCosto);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.GrupoCostos> BuscarGrupoCostoAsync(string nombreGrupoCosto) {
            return base.Channel.BuscarGrupoCostoAsync(nombreGrupoCosto);
        }
        
        public Cliente.ReferenciaRemota.Titulo BuscarTitulo(string nombreTitulo) {
            return base.Channel.BuscarTitulo(nombreTitulo);
        }
        
        public System.Threading.Tasks.Task<Cliente.ReferenciaRemota.Titulo> BuscarTituloAsync(string nombreTitulo) {
            return base.Channel.BuscarTituloAsync(nombreTitulo);
        }
        
        public void EditarContacto(int idContacto, int idCargo, int idTitulo, string nombre, string apellido, string numCedula, string correo, string numTelefonico, string celular) {
            base.Channel.EditarContacto(idContacto, idCargo, idTitulo, nombre, apellido, numCedula, correo, numTelefonico, celular);
        }
        
        public System.Threading.Tasks.Task EditarContactoAsync(int idContacto, int idCargo, int idTitulo, string nombre, string apellido, string numCedula, string correo, string numTelefonico, string celular) {
            return base.Channel.EditarContactoAsync(idContacto, idCargo, idTitulo, nombre, apellido, numCedula, correo, numTelefonico, celular);
        }
        
        public void EditarOrganizacion(int idOrganizacion, string nombreOrg, string direccionOrg, string codigoPostal, string ciudadOrg, int idProvincia, string telefonoOrg, string correoOrg, string sitioWebOrg) {
            base.Channel.EditarOrganizacion(idOrganizacion, nombreOrg, direccionOrg, codigoPostal, ciudadOrg, idProvincia, telefonoOrg, correoOrg, sitioWebOrg);
        }
        
        public System.Threading.Tasks.Task EditarOrganizacionAsync(int idOrganizacion, string nombreOrg, string direccionOrg, string codigoPostal, string ciudadOrg, int idProvincia, string telefonoOrg, string correoOrg, string sitioWebOrg) {
            return base.Channel.EditarOrganizacionAsync(idOrganizacion, nombreOrg, direccionOrg, codigoPostal, ciudadOrg, idProvincia, telefonoOrg, correoOrg, sitioWebOrg);
        }
        
        public void EditarProvincia(int idProvincia, string nombreProvincia) {
            base.Channel.EditarProvincia(idProvincia, nombreProvincia);
        }
        
        public System.Threading.Tasks.Task EditarProvinciaAsync(int idProvincia, string nombreProvincia) {
            return base.Channel.EditarProvinciaAsync(idProvincia, nombreProvincia);
        }
        
        public void EditarCargo(int idCargo, string nombreCargo) {
            base.Channel.EditarCargo(idCargo, nombreCargo);
        }
        
        public System.Threading.Tasks.Task EditarCargoAsync(int idCargo, string nombreCargo) {
            return base.Channel.EditarCargoAsync(idCargo, nombreCargo);
        }
        
        public void EditarCategoriaCorreo(int idCategoriaCorreo, string nombreCategoriaCorreo) {
            base.Channel.EditarCategoriaCorreo(idCategoriaCorreo, nombreCategoriaCorreo);
        }
        
        public System.Threading.Tasks.Task EditarCategoriaCorreoAsync(int idCategoriaCorreo, string nombreCategoriaCorreo) {
            return base.Channel.EditarCategoriaCorreoAsync(idCategoriaCorreo, nombreCategoriaCorreo);
        }
        
        public void EditarGrupoCosto(int idGrupoCosto, string nombreGrupoCosto) {
            base.Channel.EditarGrupoCosto(idGrupoCosto, nombreGrupoCosto);
        }
        
        public System.Threading.Tasks.Task EditarGrupoCostoAsync(int idGrupoCosto, string nombreGrupoCosto) {
            return base.Channel.EditarGrupoCostoAsync(idGrupoCosto, nombreGrupoCosto);
        }
        
        public void EditarTitulo(int idTitulo, string nombreTitulo) {
            base.Channel.EditarTitulo(idTitulo, nombreTitulo);
        }
        
        public System.Threading.Tasks.Task EditarTituloAsync(int idTitulo, string nombreTitulo) {
            return base.Channel.EditarTituloAsync(idTitulo, nombreTitulo);
        }
    }
}
